name: On pull request opened

on:
  pull_request:
    branches:
      - master

jobs:
  jira_labels:
    runs-on: ubuntu-latest
    name: Label Pull Request with Jira properties
    steps:
      - name: Label with Jira issue properties
        uses: xserrat/pr-jira-properties-labeler@issue_1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_ENCODED_TOKEN: ${{ secrets.JIRA_ENCODED_TOKEN }}
          JIRA_URI: ${{ secrets.JIRA_URI }}
          regexp_jira_issue_code_on_pr_title: '^([A-Z]{3}-[0-9]{4}).*'
          issue_properties: '[priority]'
